packages:
  - packages/enterprise/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': set this to true or false
  '@google/genai': set this to true or false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: set this to true or false
